import pandas as pd
import numpy as np
import os
import glob
import tqdm

# ==========================================
# 1. 配置路径和参数
# ==========================================

BASE_DIR = '/home/dongbos/Combine_optim_Borzoi_SNP'
SEARCH_ROOT = f'{BASE_DIR}/results'

# 结果保存路径 (你指定的路径)
OUTPUT_DIR = f'{BASE_DIR}/results/Fig3_multi_modal_tissue_spefic'

OUTPUT_CSV = 'Figure3_Multimodal_Gain_Summary.csv'
OUTPUT_TEX = 'Figure3_Multimodal_Gain_Summary.tex'
DETAIL_FILE = 'Figure3_Multimodal_Gain_Detailed_AllGenes.csv'

# 定义列 (Tissues) - 保持大写/小写与你文件夹命名一致
TISSUES = ['blood', 'brain', 'liver', 'heart', 'muscle', 'Pancreas']

# 定义行 (Modalities) 及其对应的文件夹/文件名特征
MODALITIES = {
    'CAGE': {
        'folder_fmt': '{tissue}_K10_borzoi_modeltrain_res',
        'file_suffix': 'optim_log.csv'
    },
    'ATAC': {
        'folder_fmt': '{tissue}_K10_borzoi_ATAC_modeltrain_res',
        'file_suffix': 'ATAC_optim_log.csv'
    },
    'DNAse': {
        'folder_fmt': '{tissue}_K10_borzoi_DNAse_modeltrain_res',
        'file_suffix': 'DNAse_optim_log.csv'
    },
    'ChIP': {
        'folder_fmt': '{tissue}_K10_borzoi_CHIP_modeltrain_res',
        'file_suffix': 'CHIP_optim_log.csv'
    }
}

# ==========================================
# 2. 核心处理函数
# ==========================================

def get_gain_stats(tissue, mod_name, mod_config):
    """
    读取特定 Tissue + Modality 下所有基因的 Log，计算平均 Gain %。
    """
    folder_name = mod_config['folder_fmt'].format(tissue=tissue)
    search_path = os.path.join(SEARCH_ROOT, folder_name, f"*{mod_config['file_suffix']}")
    
    # 查找所有结果文件
    files = glob.glob(search_path)
    
    # 如果没找到文件，返回空
    if len(files) == 0:
        # 仅在第一次找不到时打印警告，避免刷屏
        # print(f"⚠️  No files found for {tissue} - {mod_name}") 
        return 0.0, 0.0, 0, []  # Mean Pct, Mean Abs, Count, Details List

    pct_gains = []
    abs_gains = []
    gene_details = []

    for f in files:
        try:
            # 读取 CSV
            # 这里的 engine='c' 更快，但如果格式有问题可以用 'python'
            df = pd.read_csv(f)
            
            if df.empty: continue
            
            # 获取最后一步的结果 (Step 最大的一行)
            last_row = df.iloc[-1]
            
            baseline = float(last_row['Baseline'])
            gain = float(last_row['Gain'])
            
            # 提取基因名 (从文件名里解析)
            filename = os.path.basename(f)
            gene_name = filename.replace(f"_{mod_config['file_suffix']}", "")
            
            # 计算百分比增益
            # 加上 1e-6 防止 Baseline 为 0 导致除以零
            pct_gain = (gain / (baseline + 1e-9)) * 100.0
            
            pct_gains.append(pct_gain)
            abs_gains.append(gain)
            
            # 记录详细信息
            gene_details.append({
                'Tissue': tissue,
                'Modality': mod_name,
                'Gene': gene_name,
                'Baseline': baseline,
                'Gain': gain,
                'Pct_Gain': pct_gain
            })
            
        except Exception as e:
            # print(f"❌ Error reading {f}: {e}")
            continue

    # 计算平均值
    mean_pct = np.mean(pct_gains) if pct_gains else 0.0
    mean_abs = np.mean(abs_gains) if abs_gains else 0.0
    count = len(pct_gains)
    
    return mean_pct, mean_abs, count, gene_details

# ==========================================
# 3. 辅助函数：生成 LaTeX
# ==========================================

def save_latex_table(df, filepath):
    """
    生成一个漂亮的 booktabs 风格的 LaTeX 表格。
    """
    with open(filepath, 'w') as f:
        f.write("% Generated by Python script\n")
        f.write("\\begin{table}[h]\n")
        f.write("\\centering\n")
        f.write("\\caption{Average Percentage Gain of Signal Across Tissues and Modalities}\n")
        f.write("\\label{tab:multimodal_gain}\n")
        f.write("\\begin{tabular}{l" + "c" * len(df.columns) + "}\n")
        f.write("\\toprule\n")
        
        # 表头
        header = " & ".join(["\\textbf{Modality}"] + [f"\\textbf{{{c}}}" for c in df.columns]) + " \\\\\n"
        f.write(header)
        f.write("\\midrule\n")
        
        # 数据行
        for index, row in df.iterrows():
            # 将行名加粗
            line = [f"\\textbf{{{index}}}"]
            for val in row:
                # 假设 val 是字符串 "5.32%"，如果没有数据可能是 "0.00%"
                # 这里可以加逻辑：如果是该行最大值，加粗显示
                line.append(str(val))
            f.write(" & ".join(line) + " \\\\\n")
            
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")

# ==========================================
# 4. 主程序
# ==========================================

def main():
    # 确保输出目录存在
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 初始化结果矩阵 (DataFrame)
    summary_df = pd.DataFrame(index=MODALITIES.keys(), columns=TISSUES)
    
    # 初始化计数矩阵 (用于显示处理了多少个基因)
    count_df = pd.DataFrame(index=MODALITIES.keys(), columns=TISSUES)
    
    # 用来存储所有基因详细数据的列表
    all_details = []

    print("🚀 Starting to aggregate results...")
    print(f"📂 Searching folders in: {SEARCH_ROOT}")
    print("-" * 60)

    # 双重循环：遍历 Modality (行) 和 Tissue (列)
    # 使用 tqdm 显示总进度条
    total_steps = len(MODALITIES) * len(TISSUES)
    pbar = tqdm.tqdm(total=total_steps, desc="Processing")

    for mod_name, mod_config in MODALITIES.items():
        for tissue in TISSUES:
            # 获取统计数据
            mean_pct, mean_abs, count, details = get_gain_stats(tissue, mod_name, mod_config)
            
            # 填入表格 (保留 2 位小数，带百分号)
            summary_df.loc[mod_name, tissue] = f"{mean_pct:.2f}\%"
            count_df.loc[mod_name, tissue] = count
            
            # 收集详细数据
            all_details.extend(details)
            
            # 简单的实时日志
            if count > 0:
                pbar.write(f"✅ {mod_name:<6} | {tissue:<10} | N={count:<4} | Gain={mean_pct:.2f}%")
            else:
                pbar.write(f"⚠️ {mod_name:<6} | {tissue:<10} | N=0    | (Job possibly running)")
            
            pbar.update(1)

    pbar.close()

    # 5. 保存结果
    
    # 5.1 保存汇总矩阵 CSV
    csv_path = os.path.join(OUTPUT_DIR, OUTPUT_CSV)
    summary_df.to_csv(csv_path)
    
    # 5.2 保存 LaTeX
    tex_path = os.path.join(OUTPUT_DIR, OUTPUT_TEX)
    save_latex_table(summary_df, tex_path)
    
    # 5.3 保存所有基因的明细 CSV
    detail_path = os.path.join(OUTPUT_DIR, DETAIL_FILE)
    if all_details:
        details_df = pd.DataFrame(all_details)
        details_df.to_csv(detail_path, index=False)
    else:
        print("⚠️ Warning: No gene details collected (all counts were 0).")

    print("\n" + "="*60)
    print("🎉 Done! Aggregation complete.")
    print(f"📂 Output Directory: {OUTPUT_DIR}")
    print(f"   ├─ 📊 CSV Summary: {OUTPUT_CSV}")
    print(f"   ├─ 📜 TeX Table:   {OUTPUT_TEX} (Ready for Overleaf)")
    print(f"   └─ 📄 Detailed:    {DETAIL_FILE}")
    print("="*60)
    
    print("\nPreview of Summary Table (Gain %):")
    print(summary_df)
    
    print("\nPreview of Sample Counts (N genes):")
    print(count_df)

if __name__ == "__main__":
    main()